language: python
python:
  - "3.6"
sudo: false

addons:
  apt:
    packages:
    - cython
cache:
  directories:
  - "build"
  - "$HOME/.cache/pip"
install:
  - pip3 install cython
  - python3 setup.py install
script:
  - "./run_tests.sh" 
